### ISSUE TITLE
Version Dependencies 

### ISSUE THREAD

**Issue by jaxgeller** [callmecavs/outset#9]

**Comment by jaxgeller** [comment]
Not versioning is risky, can lead to lots of breaking changes.

**Comment by callmecavs** [comment]
now that Babel 6 has been released, the following changes are needed.  these will be pushed soon.  now might also be a good time to lock down the versions, though I'm hesitant to do so because this is a boilerplate

![screen shot 2015-11-04 at 10 56 12 am](https://cloud.githubusercontent.com/assets/2293641/10943549/d3a96e4a-82e2-11e5-95c6-3a44ebba0bfa.png)
![screen shot 2015-11-04 at 10 56 27 am](https://cloud.githubusercontent.com/assets/2293641/10943550/d3ac91ce-82e2-11e5-97c2-da57faf46e69.png)

**Comment by callmecavs** [comment]
for maintenance sake, I won't be versioning the dependencies in v4.0.0.  but the start script versions and installs them when run, along with running the default gulp task

**Comment by jaxgeller** [comment]
What was the final outcome, for documentation purposes?
